### ISSUE TITLE
compubench zluda

### ISSUE THREAD

**Issue by GentlemanMC** [vosen/ZLUDA#152]
the second one gave me an error and the other ones hard crash almost instantly
![image](https://github.com/vosen/ZLUDA/assets/76640636/5c66fcab-995d-466f-ac75-81b9ed6f40cd)
only level-set simulation 128 is working

**Comment by vosen** [comment]
This is a known issue. From the README:

#### CompuBench

- When running multiple tests, first test passes and the subsequent tests fail with `CUDA_ERROR_UNKNOWN`.
  
  This is a ROCm/HIP bug. Currently, CompuBench tests have to be run one at a time.

- Some tests output black screen.
  
  This is due to a bug (or an unintended hardware feature) in CompuBench that just happens to work on NVIDIA GPUs.
