### ISSUE TITLE
Error while using CUDA in 3ds max 2024 + vray

### ISSUE THREAD

**Issue by GuroniX** [vosen/ZLUDA#165]
Hello! When I try to render anything in vray gpu, I am getting this error
[21:17:26.964] Error : [RTOpenCL_impl::validate] 1: Abort was requested.
[21:17:26.968] Error : Could not initialize the GPU for rendering!
[21:17:26.975] Error : [GPU light cache] Error during GPU initialization!
Any ideas on how to fix this?
Works fine in blender tho

**Comment by Nughu** [comment]
I think this has something to do with Nvidia... Instead of spoofing V-ray into believing that a Nvidia-card is installed, Zluda seems to just keep the AMD card name. I assume that Nvidia software like this (I have the same problem with DAZs IRay) automatically blocks anything that isn't  a "NVIDIA GPU of Maxwell generation or later".

@vosen Wouldn't it be possible to somehow disguise the GPU as a Nvidia one? It has to be possible somehow, right? 
In this current situation, ZLUDA doesn't work with (presumably quite many, if not all) of those Nvidia-exclusive apps where Nvidia is in the name.

**Comment by vosen** [comment]
I have not seen any CUDA application that checks for device name and that is not the case with V-Ray. Some apps check hardware "compute capability" which is basically hardware generation. ZLUDA will allow you to spoof arbitrary compute capability for your gpu.
I've tried V-Ray benchmark, which is V-Ray with all the features cut and bundled with some predefined scenes to render.
V-Ray benchmark crashes consistently with out of range memory access early on second or third kernel dispatch. This strongly suggests it's a miscompilation: either ZLUDA translates an instruction wrong or ROCm's LLVM AMDGPU backend miscompiles emitted instructions.
The problem is that debugging this sort of problem in a complex, closed-source application is incredibly tedious and time-consuming. Weeks of full time debugging. What little time I am spending on ZLUDA right now, I am spending on other, easier to debug workloads. One of them might trigger the miscompilation affecting V-Ray.
And V-Ray has an OptiX backend, which I presume is much faster. Enabling AMD GPU non-OptiX V-Ray is very cool and interesting, but might not have as much practical utility if the NVIDIA GPU OptiX backend is much faster.

Going back to the issue: right now there's no fix. V-Ray crashing is a known issue

**Comment by GuroniX** [comment]
> I think this has something to do with Nvidia... Instead of spoofing V-ray into believing that a Nvidia-card is installed, Zluda seems to just keep the AMD card name. I assume that Nvidia software like this (I have the same problem with DAZs IRay) automatically blocks anything that isn't a "NVIDIA GPU of Maxwell generation or later".
> 
> @vosen Wouldn't it be possible to somehow disguise the GPU as a Nvidia one? It has to be possible somehow, right? In this current situation, ZLUDA doesn't work with (presumably quite many, if not all) of those Nvidia-exclusive apps where Nvidia is in the name.

I think you are right, cause when I check the RTX option in render engine, it just tries to find nvidia driver version.
![image](https://github.com/vosen/ZLUDA/assets/44945941/6748d5c2-d792-4936-bb09-f4dbc7d55fc7)
