### ISSUE TITLE
Can't Seem to Find nvcuda.dll

### ISSUE THREAD

**Issue by Idanly2** [vosen/ZLUDA#27]
Following the instructions in the readme, I successfully managed to build the project. However, being unfamiliar with cargo, I couldn't find where is the compiled package and where is the mentioned "nvcuda.dll" (searched the whole disk for it). Also, being unfamiliar with windows, it seems a little weird that copying the dll next to an existing exe will cause it to link to it. I wanted to make sure this is really how it works (sounds like some black magic voodoo).

I'll also add that as I'm using a new computer I had to install the following programs/SDK to build without errors:
- CMake
- Python3
- OpenCL installation for intel GPUs

Thank you for your help and time!

**Comment by Idanly2** [comment]
An extra initialization step required after cloning is updating the submodules:
``` git submodule update --init --recursive ```

**Comment by vosen** [comment]
I forgot to document the most important step 😊. You have to rename zluda.dll to nvcuda.dll. It's currently not done by default, because doing so breaks certain tests which rely on ZLUDA zluda.dll and NVIDIA nvcuda.dll being loaded into the same process.
I'll see what can be done to make it less confusing.

Did you build with `cargo build` or some other way (perhaps through IDE)? CMake and checking out submodules (`git submodule update --init --recursive`) is required for test targets and building with just `cargo build` should skip them.

With regards to Windows dynamic linker search path, it's documented here: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order (section "Standard Search Order for Desktop Applications"). In this particular case copying a dll into application directory is the "1. The directory from which the application loaded". Otherwise dll gets loaded using "2. The system directory" from `C:\Windows\System32\nvcuda.dll`

**Comment by vosen** [comment]
With #28 it should be better now
