### ISSUE TITLE
Downloaded AMD cuda zluda ?? VIRUS WTF??? screw YOU    HIGH THREAT LEVEL DO NOT DOWNLOAD D!CK

### ISSUE THREAD

**Issue by MetalKidRyzenX3D** [vosen/ZLUDA#92]
Program:Win32/Wacapew.C!ml

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3AWin32%2FWacapew.C!ml&threatid=265744

**Comment by MetalKidRyzenX3D** [comment]
fukking LAME AS FU*K

**Comment by Mortyyka** [comment]
MetalKidRyzenX3D

Also its open source you can just look at the code if you have half a brain cell

**Comment by hiepxanh** [comment]
It already explain in the readme, please read the content, zluda hijack Cuda process and window though it virus. You can remove it if you dont trust.

**Comment by rice7th** [comment]
Possibly use your brain before opening a useless issue. In the readme it's explained that windows flags it as a virus due to the nature of the library. Since it is opensource, you can confidently check for yourself the absence of any malicious piece of code.

**Comment by Kreijstal** [comment]
> Program:Win32/Wacapew.C!ml
> 
> https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3AWin32%2FWacapew.C!ml&threatid=265744

1st did you even read the readme?
2nd, just read the source code bro

**Comment by vosen** [comment]
@MetalKidRyzenX3D @Mortyyka @rice7th Let's all be nice here and not insult each other

I've double checked with VirusTotal and some antiviruses flag it: https://www.virustotal.com/gui/file/1943d2727c1412639f86975b9437f004a77f78d870d7537bec1e13ddd6a015c1/detection
The problem might be with you machine. Otherwise if you are worried I recommended building from sources
